### ISSUE TITLE
Component should have not more than one modifier to handle InteracionSource event

### ISSUE THREAD

**Issue by rock3r** [JetBrains/jewel#124]
Links don't react to clicks and don't get focus, both on main and in #123

**Comment by fscarponi** [comment]
Introducing Modifier.pointerHoverIcon on a clickable component will cause issues about event dispatching if the modifiers are not placed in the right order (clickable on top-> last modifier).
if a component should handle more than a simple click event, we should consider using a single PointerInput handler.

**Comment by rock3r** [comment]
Obsolete as of 0.20.0
