### ISSUE TITLE
Icons get "filled" wrong in bridge Dark theme

### ISSUE THREAD

**Issue by rock3r** [JetBrains/jewel#141]
<img width="280" alt="image" src="https://github.com/JetBrains/jewel/assets/153802/555e269e-92b7-46ef-a2b8-a9082711d70a">

Works fine when the IDE is in Light theme and old UI themes:

<img width="280" alt="image" src="https://github.com/JetBrains/jewel/assets/153802/d9ddf992-1370-4848-9b25-691edf3a2ad9">   <img width="280" alt="image" src="https://github.com/JetBrains/jewel/assets/153802/d0dd972a-a9aa-4974-9c92-59d897dc5ec2">

**Comment by devkanro** [comment]
This have been fixed in #177, I think
