### ISSUE TITLE
Support web / multiplatform / non-jvm?

### ISSUE THREAD

**Issue by CaelumF** [JetBrains/jewel#144]
Hello,

It would be great if this worked for non-jvm targets, Compose for Web targets (js and/or wasm).

I understand that right now, the main blocker for this is resource loading, particularly icons.

[Kamel](https://github.com/Kamel-Media/Kamel) and [Korim](https://docs.korge.org/korim/) can be helpful in supporting this in web and non-jvm targets.

Are there plans or thoughts regarding supporting non-jvm?

**Comment by rock3r** [comment]
Hi @CaelumF! For now the focus is desktop, but if someone wants to take up supporting non-desktop targets and can commit to it, we're open to contributions in that direction in the future.

**Comment by CaelumF** [comment]
Hey @rock3r thanks for addressing this. Makes sense. I could contribute a non-desktop target branch, but I don't think I am in a position to commit to it (assuming that means to actively keep it up to date / tested).

**Comment by rock3r** [comment]
@CaelumF yeah, we don't have enough people to maintain non-desktop, hence why we'd only consider adding it if someone was able to commit to maintaining it fully. We're open to it, but don't have enough bandwidth to do it ourselves.

**Comment by rock3r** [comment]
I'll be closing this for now since it's not in scope and we don't think we'll be providing this.
