### ISSUE TITLE
Re-evaluate SvgLoader use

### ISSUE THREAD

**Issue by rock3r** [JetBrains/jewel#167]
Is it worth having as a composition local? Is it dangerous, or unexpected, to?

**Comment by devkanro** [comment]
It's certainly worth it, if we don't want others to override this composition local, we can set it to internal and provide an easy way to get it.

```Kotlin
internal val LocalSvgLoader = compositionLocalOf<SvgLoader> {
    error("LocalSvgLoader not provided")
}

val IntelliJTheme.Companion.svgLoader
    @Composable
    @ReadOnlyComposable
    get() = LocalSvgLoader.current
```

**Comment by rock3r** [comment]
It's not about that, it's more of a philosophical question in terms of API design. Composition locals are convenient to use but potentially dangerous and must be used sparingly. This issue is a placeholder for an API discussion
