### ISSUE TITLE
Input field error states not consistent with spec

### ISSUE THREAD

**Issue by c5inco** [JetBrains/jewel#185]
- [x] Unfocused state for error and warning has extra grey inner border
- [x] Focused state for error/warning doesn't show red border over blue

Spec: https://www.figma.com/community/file/1227732692272811382/int-ui-kit

**Comment by devkanro** [comment]
There are many inconsistent issue with spec, exactly the focus holo.

**Comment by fscarponi** [comment]
I'm going to fix this behavior for Dropdowns and InputFields where this issue is so evident
