### ISSUE TITLE
Handle IDE zoom and presentation mode

### ISSUE THREAD

**Issue by rock3r** [JetBrains/jewel#217]
The IDE can set a global "zoom" level, starting in 23.2:

<img width="154" alt="image" src="https://github.com/JetBrains/jewel/assets/153802/fefd5654-325c-40a3-ad30-acf97c7f93a0">

We need to make sure we respect that. It works for text size, but not for icons/dimensions (e.g., paddings). We probably just need to adjust the LocalDensity based on the `com.intellij.ide.ui.UISettingsUtils#getCurrentIdeScale`, but also need to make sure this doesn't affect the text size.

We also need to make sure we apply the correct scaling when presentation mode is active.

**Comment by devkanro** [comment]
<img width="1512" alt="截屏2023-11-01 01 14 48" src="https://github.com/JetBrains/jewel/assets/9367842/96fdaced-ec32-4c1f-b439-803151d13555">

**Comment by devkanro** [comment]
<img width="252" alt="截屏2023-11-01 01 15 46" src="https://github.com/JetBrains/jewel/assets/9367842/4119474a-7799-4083-bd7e-97976cd33f4a">
Icon still need be scaled
