### ISSUE TITLE
Ensure buttons colours are correct in standalone mode

### ISSUE THREAD

**Issue by rock3r** [JetBrains/jewel#218]
#200 fixed button colours in the bridge, but they also look wrong in standalone.

They look like this:

![image](https://github.com/JetBrains/jewel/assets/153802/590a6e04-8a2b-46c7-981c-0ea14f3672e0)

But should look like this:

![image](https://github.com/JetBrains/jewel/assets/153802/f39ab30f-0afd-4fcc-ba22-a5be525de5cc)

**Comment by devkanro** [comment]
Fixed by #213
