### ISSUE TITLE
Selectable Lazy Column Refactoring

### ISSUE THREAD

**Issue by fscarponi** [JetBrains/jewel#220]
Due to SelectableLazyColumn usage, we found the following points that can be improved:

- [ ] SLC should directly handle the background color behaviour, so we need to introduce the SLCStyle (like we do inside the LazyTree) #158 

- [ ] Selection appearance is clipped round the edges of each element selected, but in the IDE, continuous selection is not clipped between elements

- [ ] There are some possible issues with performance that probably can be solved by using different approaches. [(info)](https://kotlinlang.slack.com/archives/C04EU44PZ4Y/p1698742541532079)

**Comment by fscarponi** [comment]
This issue will also solve:
 #100 
 #158

**Comment by rock3r** [comment]
Closing as obsolete.
