### ISSUE TITLE
Tooltips have wrong border color

### ISSUE THREAD

**Issue by rock3r** [JetBrains/jewel#243]
Theme | Swing | Jewel
--- | --- | ---
Dark | <img width="250" src="https://github.com/JetBrains/jewel/assets/153802/7e01d7bb-70fd-4030-9345-485612d64c99"> | <img width="250" src="https://github.com/JetBrains/jewel/assets/153802/5b949de7-18aa-40bb-b689-0bf9b98f83e4">
Light | (same as above) | (same as above)
Light with light header | <img width="250" src="https://github.com/JetBrains/jewel/assets/153802/947632ed-6abd-4f26-82a2-ff8db114204f"> | <img width="250" src="https://github.com/JetBrains/jewel/assets/153802/fff126dc-8d78-43e3-bac1-a43eea2d6309">

As of 0.9.0

**Comment by c5inco** [comment]
This is even worse now it seems in 23.2, as the border is closer to black in the Swing implementation:

![image](https://github.com/JetBrains/jewel/assets/1253402/4fdabc0a-5757-460e-8ffd-dcf938779dfa)

Following with IntelliJ UX team to clarify if it's expected.

**Comment by fscarponi** [comment]
@c5inco news from IJUX team?

This is the current status of the UI for tooltips **[SWING]**

| version | dark | light | light with light header |
|---------|------|-------|-------------------------|
| 232.5   |   <img width="112" alt="image" src="https://github.com/JetBrains/jewel/assets/36624359/d0f9083c-0fbd-4581-aaab-7a1690b1d2df">   |  <img width="108" alt="image" src="https://github.com/JetBrains/jewel/assets/36624359/dab571ae-685b-4cac-8174-f0a222a1311b">  |             <img width="106" alt="image" src="https://github.com/JetBrains/jewel/assets/36624359/2de87ebd-08bf-4cd8-8ec3-72d14fda57b4">       |
| 233.2   |  <img width="111" alt="image" src="https://github.com/JetBrains/jewel/assets/36624359/a83ca88a-f58f-48a6-a892-73b8cbaea10e">     |   <img width="110" alt="image" src="https://github.com/JetBrains/jewel/assets/36624359/276d010c-0684-42df-9262-e8f35fd4c157">    |          <img width="110" alt="image" src="https://github.com/JetBrains/jewel/assets/36624359/47f60101-0dde-4fb9-99cd-db84150185c6">    |

**Comment by rock3r** [comment]
@c5inco ping :)

**Comment by rock3r** [comment]
@c5inco ping again :)

**Comment by rock3r** [comment]
I think this is mostly a Swing bug, where switching themes causes the borders to be the wrong colour. @hamen please verify if this has been fixed in 242 in the platform — note you MAY need to restart the IDE after changing theme, if the light theme popup borders are still appearing black.

**Comment by hamen** [comment]
In 242, I don't see any glitch with borders:

![image](https://github.com/user-attachments/assets/e1705263-1741-49fe-a6a8-4a210cbca4a8)
![image](https://github.com/user-attachments/assets/7e7b9806-23e3-4c2b-9131-a959d6c2bc0c)
![image](https://github.com/user-attachments/assets/5e493a5c-8efc-4343-9b14-f064c5c696c5)

Ours are OK as well:
![image](https://github.com/user-attachments/assets/5a3af7d4-78ae-4e76-87ba-2637e8320bf0)
![image](https://github.com/user-attachments/assets/76a7486e-6d0c-48d2-a262-c53dafd599ec)

**Comment by rock3r** [comment]
Can you check Light with Light Header? The normal Light theme has dark tooltips, so you would not notice the dark border.

**Comment by rock3r** [comment]
It looks ok for me on 242 when switching themes in Swing. Hopefully it means they fixed their bug :)

**Comment by rock3r** [comment]
Let's consider this done for now, we'll revisit if need be.
