### ISSUE TITLE
Use DecoratedWindow for a standalone Compose desktop app

### ISSUE THREAD

**Issue by thagikura** [JetBrains/jewel#250]
Is it possible to use DecoratedWindow for a standalone Compose desktop app?

I can use DecoratedWindow for a Compose desktop app build from IDE (Android Studio), but I couldn't find if it's supported to use it for a packaged Compose desktop standalone app.

I tried to include JBR as part of the package by following steps,

1. Download   jbrsdk-17.0.9-osx-aarch64-b1000.46.pkg from https://github.com/JetBrains/JetBrainsRuntime/releases/tag/jbr-release-17.0.9b1000.46
2. Extract the JBR
3. Set the JAVA_HOME as the extracted path
4. Run the distributable by ` ./gradlew runDistributable`

But I'm seeing 
```
> Task :desktopApp:runDistributable
Exception in thread "main" java.lang.IllegalStateException: DecoratedWindow can only be used on JetBrainsRuntime(JBR) platform, please check the document https://github.com/JetBrains/jewel#int-ui-standalone-theme
        at org.jetbrains.jewel.window.DecoratedWindowKt.DecoratedWindow(DecoratedWindow.kt:65)
```

Not sure if it's even supported or I'm doing something wrong to include JBR as part of Compose desktop app.

**Comment by devkanro** [comment]
You should config JBR as your Gradle JVM and Project JVM.

Settings > Build, Execution, Deployment > Build Tools > Gradle > Gradle JVM
<img width="1136" alt="截屏2023-11-21 15 38 32" src="https://github.com/JetBrains/jewel/assets/9367842/5a6cb072-a3ed-4dc4-8beb-f6629063ba25">

File > Project Structure > Project Settings > Project > SDK
<img width="1136" alt="截屏2023-11-21 15 39 52" src="https://github.com/JetBrains/jewel/assets/9367842/c59055fa-3dda-4fb9-bcd5-e4e9041a4a34">

**Comment by devkanro** [comment]
If you using the command line to execute gradle commands, plz check gradle JVM version.

```shell
./gradlew --version
```

```log
------------------------------------------------------------
Gradle 8.4
------------------------------------------------------------

Build time:   2023-10-04 20:52:13 UTC
Revision:     e9251e572c9bd1d01e503a0dfdf43aedaeecdc3f

Kotlin:       1.9.10
Groovy:       3.0.17
Ant:          Apache Ant(TM) version 1.10.13 compiled on January 4 2023
JVM:          17.0.8.1 (JetBrains s.r.o. 17.0.8.1+7-b1070.2)
OS:           Mac OS X 13.4.1 aarch64
```

**Comment by thagikura** [comment]
Thanks!

Confirmed that it worked as a standalone Compose desktop app!
