### ISSUE TITLE
HorizontalSplitLayout ignores the minimum width set on its modifier

### ISSUE THREAD

**Issue by fscarponi** [JetBrains/jewel#263]
![image](https://github.com/JetBrains/jewel/assets/36624359/23cf4e7e-dee1-4c59-b307-2cfd8feeed29)

in the example you can drag the divider and let the second width become less than 200.dp

this is how modifier is applied on content
![image](https://github.com/JetBrains/jewel/assets/36624359/83a70ba3-2a8b-4048-aefb-6839b2d4b93a)

**Comment by rock3r** [comment]
Merged into https://github.com/JetBrains/jewel/issues/273
