### ISSUE TITLE
SplitLayout cannot be nested with the current policy

### ISSUE THREAD

**Issue by fscarponi** [JetBrains/jewel#277]
with the current implementation, creating a split pane with three panes (common use case in IJ) is possible but encounters many issues and no good code readability. (nesting 2 SplitLayouts)
As an example, resizing the window or a single pane will break the inner split pane resize if there is a min/max ratio specified, and in some cases you lose control of the divider.

**Comment by garyttierney** [comment]
Is anyone currently working on this? I need something like IJ's [ThreeComponentsSplitter](https://github.com/JetBrains/intellij-community/blob/idea/241.14494.240/platform/platform-api/src/com/intellij/openapi/ui/ThreeComponentsSplitter.kt) in a Jewel/Compose app and would be happy to look into some changes to the `SplitLayout` components to make them a bit more flexible for this use-case.

**Comment by rock3r** [comment]
I was meaning to, but didn't have time :( we'd be happy to get help on it.

I was looking at using Accompanist's [TwoPane](https://github.com/google/accompanist/blob/main/adaptive/src/main/java/com/google/accompanist/adaptive/TwoPane.kt) as a reference, minus the adaptive part, if this helps

**Comment by rock3r** [comment]
Excellent, very happy to hear this Gary :)

**Comment by rock3r** [comment]
Merged into #273
