### ISSUE TITLE
Refactoring New UI implementation based on core components

### ISSUE THREAD

**Issue by devkanro** [JetBrains/jewel#28]
## Look and feel
- [x] **Palettes** Basic colors have been added, it will be changed in future
- [x] **Painters** SVGs have been redesigned for Checkbox and Radio button, it does not copy from IJ because there are many temp icons in 22.3
- [ ] **Metrics** Just copy from Darcula theme, need check and adjust
- [x] **Typography** Change the default font to Inter

## Core component support
- [ ] **Focus style support** 
  - #34 

## Consistency check
- [x] **Check box** 
- [x] **Radio button**
  - #31
  - #32
- [x] **Buttons** Need focus style support
  - #33
- [ ] **Slider** Current implemented by swing component
- [x] **TextField** Missing round border style, focus style, heading icon and trailer icon
  - #43
  - #27
- [x] **ProgressBar** Missing implementation
  - #27
- [ ] **SegmentedButtonColors** Missing implementation
- [x] **TextArea** Missing implementation
  - #39
- [x] **Link and DropdownLink** Missing implementation
- [ ] **ToolTip** Missing implementation
- [x] **DropdownMenu** Missing implementation
- [ ] **ContextMenu** Missing implementation
- [ ] **ComboBox** Missing implementation
- [ ] **And more...**

## Consistency Issue
- #35 

## Project struct
- [ ] **Remove old impl**
- [ ] **Grallery app**

**Comment by RivanParmar** [comment]
@devkanro Are contributions allowed for this issue? If yes, then I would like to work on it.

**Comment by devkanro** [comment]
@RivanParmar  Of course, I'm now blocked by some other works, feel free to submit PRs, but don't forget to check the [manual](https://github.com/JetBrains/jewel/blob/main/CONTRIBUTING.md)

**Comment by RivanParmar** [comment]
@devkanro Are there any guidelines on how to structure the code? Since `Checkbox`, `RadioButton` and others are structured differently than each other.

**Comment by rock3r** [comment]
The guiding principle is to try and do as close to Material as possible, because that API has been iterated and battle tested a lot, and also folks are familiar with it.

And yes, this means we'll have to go back and tweak existing code in this repo...

**Comment by RivanParmar** [comment]
@rock3r What is the difference between a TextField and a TextArea? If it's same except for the number of lines, then would it be okay to implement TextField and TextArea in the same file with a common base?

**Comment by rock3r** [comment]
@RivanParmar they are very similar in functionality and the main difference is that an area is multiline and a field is not. I think it's ok for now to put them in the same file. The only thing I'd recommend is to check the swing implementation of the two and compare if they also look the same. You can use the UI inspector for that (details in the readme). The alternative is looking at the various Darcula*UI code and seeing how they work. There may be slight cosmetic differences between the two.

**Comment by devkanro** [comment]
@RivanParmar TextArea has an footer message about history, but I can't be sure if this feature is still preserved in the new ui...

https://jetbrains.design/intellij/controls/text_area/#history

**Comment by c5inco** [comment]
I have actually not seen that history feature used consistently in TextAreas in the IDE. I would not worry about having it implemented yet, as it can easily be composed together with the field itself later, and I think we should consider whether it should be coupled this way.

**Comment by devkanro** [comment]
![image](https://user-images.githubusercontent.com/9367842/230818132-a6b9b746-9821-4664-a826-1c4b4464c9c7.png)
@c5inco But these footer messages still can be found in the settings of version 23.1

**Comment by c5inco** [comment]
Sure but I'm not sure it needs to be baked in just yet. We can approach the architecture of these components differently now that we're using Compose

**Comment by devkanro** [comment]
![image](https://user-images.githubusercontent.com/9367842/230819026-6ab572e3-2111-419c-92ad-6c3af1511eac.png)
@c5inco you are right, the history has been moved to outside of text area, users can simply compose lable and text area to impl it.
