### ISSUE TITLE
Menus get drawn outside bounds and have no mouse hover effect anymore

### ISSUE THREAD

**Issue by lamba92** [JetBrains/jewel#283]
Using today's snapshot

https://github.com/JetBrains/jewel/assets/10994011/99e8a36a-3bd7-46fc-aafc-053df986fb4d

**Comment by rock3r** [comment]
Is this on the main branch? Is it happening after #282 got merged? Can you repro before?

**Comment by fscarponi** [comment]
i'm investigating,
but it seems like there are no problems in standalone
<img width="101" alt="image" src="https://github.com/JetBrains/jewel/assets/36624359/3a9cfd7c-3664-4c46-b25f-cf3aa111b60b">
but tooltips are not working at all in ide sample...

**Comment by rock3r** [comment]
Might be related https://github.com/JetBrains/compose-multiplatform/issues/4123

**Comment by rock3r** [comment]
This could be fixed in the new CfD build. As soon as it's available I'll release Jewel 0.13.1 with the update.

**Comment by rock3r** [comment]
@lamba92 I couldn't manage to get PKGS to build locally — I only confirmed that this fixes things in the Jewel IDE sample plugin. Please file subsequent issues against CMP if you still have issues.
