### ISSUE TITLE
TitleBar seems doesn't work correctly on Windows

### ISSUE THREAD

**Issue by Omico** [JetBrains/jewel#295]
See https://github.com/romainguy/kotlin-explorer/pull/7#issuecomment-1931549030

Windows 11 (10.0.22631)

**Comment by devkanro** [comment]
How do you build the menu in Windows?

<img width="113" alt="截屏2024-02-17 20 03 41" src="https://github.com/JetBrains/jewel/assets/9367842/fd8db787-345e-402e-a5fc-fa12c4455674">

When using custom titlebar the default window menu can not be used, you can add a custom menu in custom titlebar just like the JetBrains do.

<img width="85" alt="截屏2024-02-17 20 05 53" src="https://github.com/JetBrains/jewel/assets/9367842/6200f209-6e19-430d-b9b2-0f2b6861c021">

**Comment by Omico** [comment]
> How do you build the menu in Windows?
https://github.com/romainguy/kotlin-explorer/blob/136413d03f6f45811f771d5a7d6b3a9c9fa2b3c7/src/jvmMain/kotlin/dev/romainguy/kotlin/explorer/KotlinExplorer.kt#L115

**Comment by rock3r** [comment]
Is this still relevant? Is there anything we can do?

**Comment by Omico** [comment]
I have to take a look at the standalone sample. But it seems the `org.JetBrains.jewel.ui.component.Dropdown` doesn't work correctly either on https://github.com/romainguy/kotlin-explorer. 

![image](https://github.com/JetBrains/jewel/assets/14316223/b01263bf-5f16-49a8-9600-1d5e77e372f4)

**Comment by rock3r** [comment]
That's odd because we do have a drop-down in our standalone sample and we don't have issues with it (that I know of, obviously). @devkanro can you investigate when you have some time?

**Comment by devkanro** [comment]
@rock3r  sure, looking into this

**Comment by Omico** [comment]
@devkanro Yes, it has `SwingPanel` inside. I also encounter similar things like https://github.com/JetBrains/compose-multiplatform/issues/3206. 

I will rewrite all of them into Compose. Since I'm quite busy at the moment, I probably won't be able to finish it soon. You can close this issue for now.

**Comment by rock3r** [comment]
Yeah, the Swing interop has some serious limitations/issues for non-trivial use cases, as I well know. Will close for now then, let us know if things don't work correctly when using pure Compose!
