### ISSUE TITLE
:runReleaseDistributable fails with java.lang.IncompatibleClassChangeError

### ISSUE THREAD

**Issue by charlesmuchene** [JetBrains/jewel#306]
A standalone app ran using `:runReleaseDistributable` fails to launch due to the following crash:
```
Exception in thread "main" java.lang.IncompatibleClassChangeError:
class org.jetbrains.jewel.ui.painter.SvgPainterHint cannot extend
sealed interface org.jetbrains.jewel.ui.painter.PainterHint
```

Configuration:
| Dependency | Version         |
|------------|-----------------|
| Jewel      | 0.14.1          |
| Compose    | 1.6.0-dev1397   |
| JDK        | jbr-17 --arch64 |
| Kotlin     | 1.8.21          |
| Gradle     | 8.5             |

Sample project: https://github.com/charlesmuchene/sample-jewel-build-release

**Comment by rock3r** [comment]
The issue is a Proguard configuration issue, not a Jewel issue. You should either disable Proguard:

```kotlin
compose.desktop {
  buildTypes.release.proguard {
    isEnabled = false
  }
}
```

Or add the rule suggested by @devkanro to your Proguard rules file:

```
# Keep all PainterHints
-keep interface * extends org.jetbrains.jewel.ui.painter.PainterHint
```
