### ISSUE TITLE
Hi, Can proguard rules be added to the sample project

### ISSUE THREAD

**Issue by Kale1314** [JetBrains/jewel#319]
Thank you very much for your contributions, which allowed me to use this project. I encountered some trouble while using it. i enable obfuscate of  proguard, but encountered an error during startup. I am not sure what the problem is, so if there are rules in the example project, it would be great

**Comment by rock3r** [comment]
We don't have any for now and there is no short term plan to add them. However, I know some have done that and you can use their rules as a starting point. For example, https://github.com/romainguy/kotlin-explorer/blob/main/compose-desktop.pro

**Comment by rock3r** [comment]
Added a mention [in the readme](https://github.com/JetBrains/jewel?tab=readme-ov-file#using-proguardobfuscationminification) about ProGuard; closing the issue.
