### ISSUE TITLE
Improve CommonMark parsing speed by recomputing only the modified fragments.

### ISSUE THREAD

**Issue by obask** [JetBrains/jewel#333]
We can diff changed blocks by running commonmark with this parameter `.includeSourceSpans(IncludeSourceSpans.BLOCKS)` and then finding the first and the last unchanged fragment of a string. Then run commonmark on items in between and replace these blocks in the Document's children list.

**Comment by rock3r** [comment]
@obask is there more work to do beyond what #337 brought in? Can we close this issue?
