### ISSUE TITLE
MenuScope::separator doesn't seem to do anything

### ISSUE THREAD

**Issue by juancnuno** [JetBrains/jewel#358]
```kotlin
    Dropdown(
      Modifier.padding(end = Padding.MEDIUM),
      menuContent = {
        Service.values().forEach {
          selectableItem(selectedService == it, onClick = { onSelectedServiceChange(it) }) {
            Text(it.toString())
          }
        }

        separator()

        selectableItem(selectedService == null, onClick = { onSelectedServiceChange(null) }) {
          Text("Show All")
        }
      },
    ) {
      Text(selectedService.toString())
    }
```
results in

![Screenshot from 2024-04-17 12-49-47](https://github.com/JetBrains/jewel/assets/13580393/9969f95d-3e85-47d2-9103-59ff62af386f)

I don't see a separator there

**Comment by rock3r** [comment]
I can't repro this in standalone:

<img width="199" alt="image" src="https://github.com/JetBrains/jewel/assets/153802/0eb1c53c-d5dd-452b-9743-b7b7c6af287c">

This might be a bridge-only issue. Looking into it.
