### ISSUE TITLE
Stand-alone sample app crashes on progress indicator when switching themes

### ISSUE THREAD

**Issue by krm1312** [JetBrains/jewel#359]
MacOS Sonoma 14.4.1
Apple M3
JBR-17.0.10+1-1207.14-jcef

Reproduction Steps:

Stand-alone sample app -> System theme -> Components -> ProgressBar

Then click switch theme.  Sample-app almost always crashes on first or second theme switch.

<img width="800" alt="image" src="https://github.com/JetBrains/jewel/assets/532397/621f7172-c8fc-411e-ba3f-b2ec5aaa1cf9">

> Exception in thread "AWT-EventQueue-0" java.lang.IndexOutOfBoundsException: index: 7, size: 0
> 	at androidx.compose.runtime.external.kotlinx.collections.immutable.internal.ListImplementation.checkElementIndex$runtime(ListImplementation.kt:15)
> 	at androidx.compose.runtime.external.kotlinx.collections.immutable.implementations.immutableList.SmallPersistentVector.get(SmallPersistentVector.kt:146)
> 	at androidx.compose.runtime.snapshots.SnapshotStateList.get(SnapshotStateList.kt:92)
> 	at org.jetbrains.jewel.ui.component.CircularProgressIndicatorKt.CircularProgressIndicatorImpl-coD9juw(CircularProgressIndicator.kt:113)
> 	at org.jetbrains.jewel.ui.component.CircularProgressIndicatorKt.access$CircularProgressIndicatorImpl-coD9juw(CircularProgressIndicator.kt:1)
> 	at org.jetbrains.jewel.ui.component.CircularProgressIndicatorKt$CircularProgressIndicatorImpl$2.invoke(CircularProgressIndicator.kt)
> 	at org.jetbrains.jewel.ui.component.CircularProgressIndicatorKt$CircularProgressIndicatorImpl$2.invoke(CircularProgressIndicator.kt)
> 	at androidx.compose.runtime.RecomposeScopeImpl.compose(RecomposeScopeImpl.kt:192)
> 	at androidx.compose.runtime.ComposerImpl.recomposeToGroupEnd(Composer.kt:2557)
> 	at androidx.compose.runtime.ComposerImpl.skipToGroupEnd(Composer.kt:2851)
> 	at org.jetbrains.jewel.ui.component.CircularProgressIndicatorKt.CircularProgressIndicator(CircularProgressIndicator.kt:50)
> 	at org.jetbrains.jewel.samples.standalone.view.component.ProgressBarKt.ProgressBar(ProgressBar.kt:106)
> 	at org.jetbrains.jewel.samples.standalone.view.component.ProgressBarKt$ProgressBar$7.invoke(ProgressBar.kt)
> 	at org.jetbrains.jewel.samples.standalone.view.component.ProgressBarKt$ProgressBar$7.invoke(ProgressBar.kt)
> 	at androidx.compose.runtime.RecomposeScopeImpl.compose(RecomposeScopeImpl.kt:192)
> 	at androidx.compose.runtime.ComposerImpl.recomposeToGroupEnd(Composer.kt:2557)
> 	at androidx.compose.runtime.ComposerImpl.skipCurrentGroup(Composer.kt:2828)
> 	at androidx.compose.runtime.ComposerImpl.doCompose(Composer.kt:3315)
> 	at androidx.compose.runtime.ComposerImpl.recompose$runtime(Composer.kt:3266)
> 	at androidx.compose.runtime.CompositionImpl.recompose(Composition.kt:940)
> 	at androidx.compose.runtime.Recomposer.performRecompose(Recomposer.kt:1155)
> 	at androidx.compose.runtime.Recomposer.access$performRecompose(Recomposer.kt:127)
> 	at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$1.invoke(Recomposer.kt:583)
> 	at androidx.compose.runtime.Recomposer$runRecomposeAndApplyChanges$2$1.invoke(Recomposer.kt:551)
> 	at androidx.compose.runtime.BroadcastFrameClock$FrameAwaiter.resume(BroadcastFrameClock.kt:42)
> 	at androidx.compose.runtime.BroadcastFrameClock.sendFrame(BroadcastFrameClock.kt:71)
> 	at androidx.compose.ui.scene.BaseComposeScene.render(BaseComposeScene.skiko.kt:160)
> 	at androidx.compose.ui.scene.ComposeSceneMediator.onRender(ComposeSceneMediator.desktop.kt:534)
> 	at org.jetbrains.skiko.SkiaLayer.update$skiko(SkiaLayer.awt.kt:485)
> 	at org.jetbrains.skiko.redrawer.AWTRedrawer.update(AWTRedrawer.kt:54)
> 	at org.jetbrains.skiko.redrawer.MetalRedrawer$frameDispatcher$1.invokeSuspend(MetalRedrawer.kt:82)
> 	at org.jetbrains.skiko.redrawer.MetalRedrawer$frameDispatcher$1.invoke(MetalRedrawer.kt)
> 	at org.jetbrains.skiko.redrawer.MetalRedrawer$frameDispatcher$1.invoke(MetalRedrawer.kt)
> 	at org.jetbrains.skiko.FrameDispatcher$job$1.invokeSuspend(FrameDispatcher.kt:33)
> 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
> 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
> 	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
> 	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:792)
> 	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:739)
> 	at java.desktop/java.awt.EventQueue$3.run(EventQueue.java:733)
> 	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
> 	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
> 	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:761)
> 	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
> 	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
> 	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
> 	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
> 	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
> 	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
> 	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [androidx.compose.ui.scene.ComposeContainer$DesktopCoroutineExceptionHandler@e0c19de, androidx.compose.runtime.BroadcastFrameClock@4def8f25, StandaloneCoroutine{Cancelling}@99b8c11, FlushCoroutineDispatcher@600986ea]

**Comment by rock3r** [comment]
Thanks for the report, will try to fix asap
