### ISSUE TITLE
`Text` composable doesn't use color from TextStyle

### ISSUE THREAD

**Issue by garyttierney** [JetBrains/jewel#369]
Hi,

Not sure if this is intentional or a bug, so happy to send a PR up if it's the latter. When composing `Text` it uses the following for color, in order:

1. `color` parameter (defaults to `Unspecified`)
2. `LocalContentColor.current`
3. `style.color` parameter (defaults to `JewelTheme.defaultTextStyle.color`, which is also unspecified)

https://github.com/JetBrains/jewel/blob/main/ui/src/main/kotlin/org/jetbrains/jewel/ui/component/Text.kt#L82

Should the order of 2 and 3 actually be switched? So:

```kt
    val textColor = color.takeOrElse { style.color.takeOrElse { LocalContentColor.current } }
```

**Comment by rock3r** [comment]
I seem to remember this was done on purpose to fix a scenario where the LocalContentColor wasn't applied, but it was a long time ago and I am not sure what the issue was. @devkanro maybe remembers?

Can you confirm if this is happening in the standalone, or bridge, or both themes?

**Comment by garyttierney** [comment]
> Can you confirm if this is happening in the standalone, or bridge, or both themes?

Ah sorry, should've specified, this is in standalone (haven't tested bridge).

**Comment by rock3r** [comment]
Thanks. Let's see if @devkanro has any recollections on the why that is that way :)

**Comment by devkanro** [comment]
LocalContentColor used to override text color which has focused style(background is blue, and foreground is white).
So I make the LocalContentColor has higher policy than color in style, those style will not be changed when control state changed.

**Comment by garyttierney** [comment]
Ah, that makes sense. I was using `TextStyle`s for styles like hints and secondary text, but maybe it's more appropriate for me to use `TextStyle` solely for font/typesetting information and represent the colors separately. Thanks for the quick response!

**Comment by rock3r** [comment]
@garyttierney should we close the issue? Seems like we have at least a clear idea why this is :)

**Comment by garyttierney** [comment]
Yep, happy to close. Thanks for all the hard work on this awesome UI kit :)
