### ISSUE TITLE
Jewel theme text style is not applied in markdown blocks

### ISSUE THREAD

**Issue by Yashobanta-Kumar-Behera** [JetBrains/jewel#370]
As i can see in the file MarkdownIntUiStyling the following text size is hardcoded

```kotlin
private val defaultTextSize = 13.sp

private val defaultTextStyle
    get() =
        JewelTheme.createDefaultTextStyle(
            fontSize = defaultTextSize,
            lineHeight = defaultTextSize * 1.5,
        )
```

Is this done intentionally or support can be added to override text size in default markdown styling

**Comment by rock3r** [comment]
You can use the markdown styling constructor to provide a different base text style with whatever size you prefer

**Comment by rock3r** [comment]
To be clear the Markdown styling is still very new and will improve over time. One thing it should probably do is to use the other composition locals (content colour and text style) to define the base text style.

**Comment by Yashobanta-Kumar-Behera** [comment]
Yes I am clear but in order to change only text size have to build entire Markdown styling elements.

**Comment by rock3r** [comment]
Yes, see previous comment.

**Comment by Yashobanta-Kumar-Behera** [comment]
Ok Thanks
