### ISSUE TITLE
Review `Scrollbars.kt`

### ISSUE THREAD

**Issue by morozkin** [JetBrains/jewel#395]
- [ ] Make sure the same approach for `hoverDurationMillis` is used among all scroll bars
- [ ] `remember` should be used with `key` as values are based on `style` and must reflect changes in `style`
- [ ] `remember` values instead of `MutableState` (`val shape = remember { RoundedCornerShape(style.metrics.thumbCornerSize) }` instead of `val shape by remember { mutableStateOf(RoundedCornerShape(style.metrics.thumbCornerSize)) }`)

Discussed [here](https://github.com/JetBrains/jewel/pull/394#issuecomment-2152645902)

**Comment by rock3r** [comment]
Probably made obsolete by the work on #445

**Comment by hamen** [comment]
#521 should cover this
