### ISSUE TITLE
Fonts loaded from classpath are missing

### ISSUE THREAD

**Issue by lamba92** [JetBrains/jewel#4]
IntelliJ loads JetBrains Mono from a file in the classpath resources. The current Skiko font loading machinery does not see it. See function `retrieveFont` for details.

**Comment by rock3r** [comment]
Can we test again and close if fixed @lamba92 ?

**Comment by rock3r** [comment]
Obsolete (being worked on in https://github.com/JetBrains/skiko/pull/639)
