### ISSUE TITLE
new ui TextArea cannot enter

### ISSUE THREAD

**Issue by ergouliang** [JetBrains/jewel#41]
run samples -> standalone-new-ui ，TextArea Can't enter information
![image](https://user-images.githubusercontent.com/8575496/233973966-c39cc121-2da5-4f79-ad23-fe2fe42a85dc.png)

**Comment by devkanro** [comment]
The sample don't handle the text changed event, so you can't enter text on it
ref the code: [Main.kt#L296](https://github.com/JetBrains/jewel/blob/main/samples/standalone-new-ui/src/main/kotlin/org/jetbrains/jewel/samples/standalone/expui/Main.kt#L296)

You can use it by 
```Kotlin
var text by remember { mutableStateOf("This is a text area\nIt can be multiline") }
TextArea(text, { text = it })
```

**Comment by devkanro** [comment]
The current implementation of the new UI is directly copied from the ButterCam/compose-jetbrains-them project.

We're working on cleaning up and refactoring this code to blend in with jewel's original code.

In the meantime, we recommend that you do not use this project for production.

**Comment by ergouliang** [comment]
> The current implementation of the new UI is directly copied from the ButterCam/compose-jetbrains-them project.
> 
> We're working on cleaning up and refactoring this code to blend in with jewel's original code.
> 
> In the meantime, we recommend that you do not use this project for production.

thank you for your reply, I will continue to pay attention
