### ISSUE TITLE
Sample standalone code does not build on Windows 10

### ISSUE THREAD

**Issue by askolt** [JetBrains/jewel#414]
I tried run the sample code and got an error
```
Exception in thread "main" java.lang.NoClassDefFoundError: org/jetbrains/jewel/samples/standalone/view/ComponentsViewKt (wrong name: org/jetbrains/jewel/samples/standalone/view\ComponentsViewKt)
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1017)
```
In `org/jetbrains/jewel/samples/standalone/reflection/Views.kt:44` just add a new line with replace `\` to `.`. It's work fine for me.

```
    val fullyQualifiedClassName =
        packageName +
            f.absolutePathString().removePrefix(directory.absolutePathString())
                .dropLast(6) // remove .class
                .replace('/', '.')
                .replace('\\', '.') // for Win10
```

**Comment by rock3r** [comment]
Hi @askolt, I just tried running the sample on Windows 11 and it works just fine as it is on `main`:

![image](https://github.com/JetBrains/jewel/assets/153802/a56f2295-057e-4633-b58f-70234a30f804)

I'm not sure what's going on, but I am not very inclined to making changes for issues I can't repro. Are you sure you're using the latest JBR to run? I don't know if it makes any difference, but it's the only factor at play here.

**Comment by askolt** [comment]
Maybe on Windows 11 it works, but on Windows 10 Home 22H2 got an error . 😅

**Comment by rock3r** [comment]
I don't have a way to test/validate the fix on W10, as I only have W11 — even work computers don't have W10 anymore 😅  But feel free to open a PR if that unblocks you
