### ISSUE TITLE
Iterate on scrollbars

### ISSUE THREAD

**Issue by hamen** [JetBrains/jewel#445]
Based on the initial work in #419, we need to add:

* [ ] On hover, scrollbar width grows to `14.dp`
* [x] Scrollbar track must be visible when the scrollbar is engaged
* [ ] Track must be clickable to allow scrollToPosition or scrollByOnePage
* [x] The scrollbar is hidden by default unless the user starts scrolling
* [x] The scrollbar disappears after an inactivity period of N seconds

The following image shows how this works in the current non-Jewel implementation:

![Screen Recording 2024-07-12 at 13 19 48](https://github.com/user-attachments/assets/2ff1d536-66cf-49a4-be10-f1c48ae8ca3f)

**Comment by rock3r** [comment]
Swing reference code: `com.intellij.ui.components.MacScrollBarUI`
