### ISSUE TITLE
Automate IntUI palette generation

### ISSUE THREAD

**Issue by rock3r** [JetBrains/jewel#47]
The IntUI palette is currently generated by hand, but it could be obtained programmatically from https://github.com/JetBrains/intellij-community/blob/master/platform/platform-resources/src/themes/expUI/expUI_light.theme.json and https://github.com/JetBrains/intellij-community/blob/master/platform/platform-resources/src/themes/expUI/expUI_dark.theme.json

**Comment by devkanro** [comment]
This has been fixed in 
- #46
