### ISSUE TITLE
Textarea: Tab doesn't work same as Swing

### ISSUE THREAD

**Issue by francisconoriega** [JetBrains/jewel#497]
Pressing Tab in a swing textarea inputs a tab, but doing it in compose version inputs a space.

https://github.com/user-attachments/assets/117d53e4-6510-4e23-99ee-fe3d37e22726

**Comment by rock3r** [comment]
I'm aware, however I believe this should be fixed at the Compose level, at least for desktop

**Comment by rock3r** [comment]
For the record, the way I solved this in my use case is (going by memory, code may not compile):

```kotlin
val focusManager = LocalFocusManager.current

TextArea(..., Modifier.onPreviewKeyPress { event ->
  if (event.key == Key.Tab && event.eventType = KeyEventType.Down) {
    focusManager.moveFocus(FocusDirection.Next)
    true
  } else {
    false
  }
}
```

Closing this issue, as I have filed https://youtrack.jetbrains.com/issue/CMP-5822/Multiline-BasicTextField-swallows-tab-keypresses
