### ISSUE TITLE
Make Dropdown have generic content popup

### ISSUE THREAD

**Issue by rock3r** [JetBrains/jewel#529]
Once #528 is done, dropdowns (and link dropdowns) should provide a slot API for the popup contents, instead of mandating the use of a MenuScope. This will make them more flexible.

We can retain the current menu-based dropdowns for simple cases with few items, by rebuilding the current implementation on top of the slot-based one.

**Comment by rock3r** [comment]
@hamen this is done, correct?

**Comment by hamen** [comment]
The `ComboBox` has a slot to accept a generic Composable as `popupContent`, so I would say "Yes, it's done".

**Comment by rock3r** [comment]
Then it shall be closed
