### ISSUE TITLE
OverrideDarkMode doesn't work as expected

### ISSUE THREAD

**Issue by francisconoriega** [JetBrains/jewel#550]
OverrideDarkMode doesn't really sets the composition to use darkmode values, which what I would expect.

Example, given:

```
// running in Light UI
Box(modifier = Modifier.background(Color.Black)
    OverrideDarkMode(isDark = true) {
       Text("Hello").
    }
}
```
I'd expect the text/LocalContentColor to be set to  to DarkPalette, grey 12:

<img width="500" alt="image" src="https://github.com/user-attachments/assets/0ffcd84d-350b-4ede-b741-07dc6c866aeb">

but instead I get LightPalette grey1:
<img width="500" alt="image" src="https://github.com/user-attachments/assets/d652a0a9-e518-41a9-aecf-44dbbd6e9918">

which is unreadable against a dark background

**Comment by rock3r** [comment]
`OverrideDarkMode` sets the `isDark` value, which is generally then used to pick which theme to use. It does nothing more than that — you're still responsible for setting a theme inside if needed. The reason for this is that, if you want to change the theme for a specific section of your UI, you need to... set the theme:

```kotlin
fun main() = singleWindowApplication {
  JewelTheme(isDark = false) {
    Column {
      Text("I am light")
      JewelTheme(isDark = true) {
        Text("I am dark")
      }
    }
  }
}
```

`OverrideDarkMode` can't know how you want your theme to be (what if you want to customize anything?), so it will never be able to do what you expected. I understand where the confusion comes from, but IIRC this API was necessary strictly for setting up something in the decorated title bars, which can have a different `isDark` value than the rest of the UI.

The "fix" here is to add some KDocs to `OverrideDarkMode` to explain what it does and doesn't, and point to setting the theme instead in your use case.

**Comment by francisconoriega** [comment]
Thanks for the explanation, I guess the name (with no further KDoc) is a bit confusing, thanks for the example!
