### ISSUE TITLE
Design new demo app

### ISSUE THREAD

**Issue by rock3r** [JetBrains/jewel#57]
The current demo app is very barebones. We would like to get something a bit nicer that a collection of widgets, to showcase how to use Jewel.

The mockup can contain components we don't have yet, and we can backfill the gaps as we go.

**Comment by rock3r** [comment]
@c5inco any plan to do this? Or should we close for now?

**Comment by c5inco** [comment]
The design is fine right now so let's close it and can reopen if it's a higher priority
