### ISSUE TITLE
Text Component has wrong order for color

### ISSUE THREAD

**Issue by francisconoriega** [JetBrains/jewel#591]
Or at least it is not what Material uses.

When trying to figure out colors material uses:

    val textColor = color.takeOrElse { style.color.takeOrElse { LocalContentColor.current } }

where as Jewel uses

    val textColor = color.takeOrElse { LocalContentColor.current.takeOrElse { style.color } }

this means that in the next example, in Material it is possible to have the icon be blue and text be red, but in Jewel it is not possible, since `LocalContentColor` always wins so you get  a blue icon and a blue text.

```
  CompositionLocalProvider(
      LocalTextStyle provides LocalTextStyle.current.copy(color = Color.Red),
      LocalContentColor provides Color.Blue,
  ) {
      IconAndText()
  }

  @Composable
  fun IconAndText() {
      Row {
          Icon()
          Text(
              text = text,
          )
      }
  }

```

its a very small PR I can submit if you agree with this

**Comment by rock3r** [comment]
I remember we changed this to fix a bug where text was not being displayed properly. At a quick look, this comes up: https://github.com/JetBrains/jewel/pull/180/files#r1361761781

Feel free to open a PR, but please text _extensively_ to make sure nothing breaks, both in Standalone and Bridge!
