### ISSUE TITLE
CommonMark 0.23 & InlineContent

### ISSUE THREAD

**Issue by francisconoriega** [JetBrains/jewel#600]
I saw that CommonMark released version [0.23](https://github.com/commonmark/commonmark-java/blob/main/CHANGELOG.md), which includes new ways to set custom inline rendering. Should we update to it, and is do you think this will impact the current inline rendering extensions setup we have?

**Comment by rock3r** [comment]
I'll look into it but I'd generally be keen on any meliorative updates

**Comment by rock3r** [comment]
Looks like a good update to grab. Any chance you could contribute to this?

**Comment by francisconoriega** [comment]
I might have a little bit of time tomorrow, I'll check out and let you know if I'll have a chance, but if its not this week I wouldn't be able, since I'm traveling the next couple of weeks after.

**Comment by rock3r** [comment]
Absolutely, no pressure. If it's not this week I think we may be able to pick it up next week or the following one

**Comment by obask** [comment]
I think we use hand-written rendering extensions, and this version only update custom parsing which we don't use directly. However having `getInputIndex` in 0.24.0 should let us simplify quick edit logic.
