### ISSUE TITLE
Checkbox and RadioButton have extra start padding

### ISSUE THREAD

**Issue by francisconoriega** [JetBrains/jewel#646]
Checkboxes and RadioButton are adding an extra start padding that is not present in the swing implementation, which makes it hard to align elements in a screen.

IntelliJ: 

<img width="178" alt="image" src="https://github.com/user-attachments/assets/0763aecd-abcf-4840-bfd5-34e78b3accf8">

Jewel
<img width="261" alt="image" src="https://github.com/user-attachments/assets/95e32712-f346-48c7-9203-24efed9cf4c6">

**Comment by francisconoriega** [comment]
it seems like the issue comes the asset used, it has padding around it: 

ExisCheckbox code + just adding a black background:

 
<img width="837" alt="image" src="https://github.com/user-attachments/assets/c1b43c39-b0f3-45f6-aa8d-f1f800a6adf6">


<img width="286" alt="image" src="https://github.com/user-attachments/assets/9963f3c3-be7f-4c29-9872-7a241681b7b3">

**Comment by kirill-grouchnikov** [comment]
Isn’t that space for the focus indication?

**Comment by francisconoriega** [comment]
@kirill-grouchnikov then I think that the implementation for the focus is not quite correct, it shouldn't need to take/reserve space, and the indication should be drawn outside the bounds of the composable

**Comment by rock3r** [comment]
Those assets come from the platform (in standalone they're copied from it, in bridge they're loaded directly).

The blank space is indeed for focus indication. Our components handle this the same way as the platform: everything is delegated to the svg. We just draw the correct one based on state.

**Comment by rock3r** [comment]
I don't remember if the platform does special casing in the layouts and effectively adds a negative margin to compensate, or the components draw outside their bounds. I don't think in Swing you can do (or at least, normally do) the latter, so the special casing wouldn't surprise me. 

Buttons and all other Swing components that draw a focus ring also reserve space for it, by the way.

**Comment by rock3r** [comment]
I checked and indeed, the Kotlin UI DSL adds a start-side margin to labels under the hood to align them with the other components. That is what you also need to do in Compose — except you will need to do it for all components that are not a CheckBox or a RadioButton, since we don't need/have the extra margin around Buttons, TextField/TextArea, etc for the focus ring.

Maybe one day we'll have a Compose Form DSL to take care of this automatically, but that day is not today :D

**Comment by francisconoriega** [comment]
@rock3r Perhaps Jewel could expose a variable that has the official DPs needed to align things? Just thinking it would benefit anyone else trying to make a form rn

**Comment by rock3r** [comment]
I don't think that is particularly helpful, because you still need to know which components to apply it to, and do all that work by hand. Plus, the value is not likely going to change over time, so I don't think it brings much value.
