### ISSUE TITLE
Remove rounded corner from ListComboBox selected item

### ISSUE THREAD

**Issue by hamen** [JetBrains/jewel#650]
![image](https://github.com/user-attachments/assets/340fe87f-9d3c-49c7-92d6-ffcaa736f2e4)

Relates to #627 
Follows #631

**Comment by rock3r** [comment]
That screenshot shows no rounded corners to remove, can you clarify?

**Comment by hamen** [comment]
Swing:
![image](https://github.com/user-attachments/assets/c1f725b6-adee-42bf-945d-59697ed4cec3)

Jewel with the fix
![image](https://github.com/user-attachments/assets/f6735c4c-c4d3-437f-a25b-446cf303d816)
Jewel with the bug
![image](https://github.com/user-attachments/assets/6ee07617-b0d9-47d5-b86d-dab5d0b45bf1)

**Comment by rock3r** [comment]
Ah I didn't zoom in enough :)

Thanks!

**Comment by hamen** [comment]
YYEEEEEEEEEEEEEEEEEEEEEEEEEEEEEESSS!!!!!!
IT HAPPENED!!! I SAW SOMETHING YOU DIDN'T SEE!!!
THE UX ENGINEER FORCE IS STARTING TO FLOW IN ME!!!
![HomerSimpsonWhooHooGIF](https://github.com/user-attachments/assets/ac986f26-99da-4a4e-8170-79a99a6ec6bb)

**Comment by rock3r** [comment]
![](https://i.giphy.com/media/v1.Y2lkPTc5MGI3NjExM2Y2MTdrOTRsdDFzd3cxNHdnOGg3MG8ybGo0cDR4ZXJlMjhweTJzeiZlcD12MV9pbnRlcm5hbF9naWZfYnlfaWQmY3Q9Zw/x6WhgtmAIbgMU/giphy.gif)

**Comment by hamen** [comment]
Closed by #651
