### ISSUE TITLE
SplitLayout divider position changes when moved between screens of different densities

### ISSUE THREAD

**Issue by rosejr** [JetBrains/jewel#661]
This requires two monitors with different display densities (in my case MacBook with Retina display and 2560x1600 external monitor).

1. Create window containing split layout on low DPI screen
2. Move window to high DPI screen
3. Split layout position is to the left of where it was on the previous screen
4. If you then grab the divider to adjust it, it snaps back to where it should be

The opposite happens going from high-DPI to low-DPI (the divider moves to the right).

**Comment by rock3r** [comment]
Probably related to the other bug

**Comment by hamen** [comment]
Relates to #589
