### ISSUE TITLE
Disabled options text color is incorrect in `Dropdown` component

### ISSUE THREAD

**Issue by YasserDbeis** [JetBrains/jewel#668]
I am an engineer for Android Studio Profiler which, as of Koala Feature Drop, has been using Jewel for the home tab implementation. Recently we had the following bug reported: https://b.corp.google.com/issues/376056212. This was also reproduced in another area of Studio that employs Jewel (`Device Manager` > `Add a new device`). This issue first appeared in Ladybug Feature Drop, and was not present in Koala Feature Drop nor Ladybug 1.

Essentially, the issue can be summarized as, when a single disabled dropdown option, or even if the dropdown itself is disabled, the text color shown makes it look like its enabled.

To reproduce, I simply cloned the jewel project, set `enabled` equal to `false` for the only `Dropdown` in the `ComposeShowcaseTab` and ran the IDE Sample. Here is the result:
<img width="169" alt="image" src="https://github.com/user-attachments/assets/0a937c95-dcf9-4303-9e18-46c01be80f80">

**Comment by rock3r** [comment]
@hamen can you take a look? This is in the old dropdowns, but feels like the bug is actually in the menu items

**Comment by hamen** [comment]
I'm looking into it today 🤞

**Comment by YasserDbeis** [comment]
Thanks!!!

**Comment by YasserDbeis** [comment]
Studio just got jewel 0.27.0 which I confirmed contains this fix, but I just tried it out and it seems like the disabled entry still looks enabled?

In this example, the "Process start" entry is unselectable and disabled, but looks like its not. Also, this might be unrelated, but it seems like the dropdown ui changed as well? Options are much thinner than before.
<img width="451" alt="image" src="https://github.com/user-attachments/assets/ef7f871d-df13-4c55-80fc-aefb0ec70756">

**Comment by rock3r** [comment]
Thanks Yasser. Will have Ivan look into this again next week.

**Comment by hamen** [comment]
I have a fix in https://github.com/JetBrains/jewel/pull/717

**Comment by YasserDbeis** [comment]
Thanks! Will this also address the issue where the dropdown options look much thinner now?

**Comment by hamen** [comment]
Unfortunately, no, the reason being https://github.com/JetBrains/jewel/pull/718.
We are close to releasing an on-spec, polished new version of the old `Dropdown`, called `ListComboBox`, that is properly mirroring what Swing currently does: https://github.com/JetBrains/jewel/pull/715.
No rush to migrate, but you should definitely check it out once we release this latest iteration.
