### ISSUE TITLE
Failed to check JDK distribution: 'jpackage' is missing

### ISSUE THREAD

**Issue by crowforkotlin** [JetBrains/jewel#709]
I use jewel in my project, which requires jbrsdk+jcef but I see that jbr doesn't have jpackage, so when I use ./gradlew packageDmg, I get an error!
![image](https://github.com/user-attachments/assets/dbaecbd4-d6a0-4e15-b21a-1484f73dfe20)
Is there a way around this?

Jewel must be run with jbr, but jbr does not have jpackage. I cannot package it on Mac. If I force the packaged product, it will not run.

**Comment by rock3r** [comment]
I think it's fine to use different JDKs to build and run, if that is the question.

**Comment by crowforkotlin** [comment]
> I think it's fine to use different JDKs to build and run, if that is the question.如果这是个问题，我认为使用不同的 JDK 来构建和运行是可以的。

<img width="951" alt="image" src="https://github.com/user-attachments/assets/85310ec0-70f7-4d4e-ada0-1f77ea1b72e8">

**Comment by crowforkotlin** [comment]
> I think it's fine to use different JDKs to build and run, if that is the question.如果这是个问题，我认为使用不同的 JDK 来构建和运行是可以的。

It can be packaged, but it will crash when running. JBR must be used. I use jbr on the Windows desktop. If I change to other jdk, the packaging will also fail? I seem to remember this error java.lang.IllegalStateException: DecoratedWindow can only be used on JetBrainsRuntime (JBR) platform

**Comment by crowforkotlin** [comment]
> I think it's fine to use different JDKs to build and run, if that is the question.如果这是个问题，我认为使用不同的 JDK 来构建和运行是可以的。

At present, I can package on Windows, using jbr, and it runs normally, but on Mac, I need to use jpackage, which makes me wonder how to solve it. I checked all jdk17 packages of jbr and found that jbr does not exist at all

**Comment by rock3r** [comment]
You need to package with another JDK, and still run with JBR.

We don't have the capacity to offer support for other libraries, tools, and technologies, unfortunately. I'd recommend you consulting the appropriate documentation (for jpackage etc) to see how this could be done.

When it's finally fully working, you can also look at https://github.com/JetBrains/jewel/pull/289 — however, that is only an example on how you could do your packaging and distribution and is provided as a reference with no support, either.

**Comment by crowforkotlin** [comment]
https://github.com/kaleidot725/AdbPad/issues/106
The same question has not yet been completely solved. I don't know how to package the cross-compiled library. This problem occurs when using gradlew packageDmg and has not been completely solved. But I replaced it with another open source library for packaging on Mac, "dev.hydraulic.conveyor:conveyor-control", and now it works.

**Comment by crowforkotlin** [comment]
> Collaborator

https://github.com/kaleidot725/AdbPad/issues/106
The same question has not yet been completely solved. I don't know how to package the cross-compiled library. This problem occurs when using gradlew packageDmg and has not been completely solved. But I replaced it with another open source library for packaging on Mac, "dev.hydraulic.conveyor:conveyor-control", and now it works.
