### ISSUE TITLE
Update Compose to 1.8.0

### ISSUE THREAD

**Issue by rock3r** [JetBrains/jewel#725]
Compose Multiplatform 1.8.0-alpha01 is out and we should adopt it asap, as it includes important fixes we were waiting for.

We should also take care of #666 in the process

**Comment by criticalstrike18** [comment]
may i be allowed to this

**Comment by rock3r** [comment]
@criticalstrike18 I think @hamen is going to do it soon as part of other work. You can update the dependency locally in your project in the meantime, it shouldn't break (but we haven't tested yet)
