### ISSUE TITLE
Create wrapper for IDE platform icons

### ISSUE THREAD

**Issue by rock3r** [JetBrains/jewel#73]
Standalone is optional, but at least in the IDE theme we should have an easy way to address platform icons (AllIcons, StudioIcons, etc). This should be auto-generated from IDE sources.

**Comment by Walingar** [comment]
For now the way to address icons is to use Icon(key, classloader). Where the algorithm is: 
1. Find class where icon placed (like AllIcons)
2. find icon there
3. copy id from there
4. Use it's class classloader

In the future IntelliJ Platform may provide just keys for Icons, so they can be used without classloader. But for now the only way is described one

**Comment by Walingar** [comment]
I am not aware of such issue, it was just 1n1 discussions

**Comment by rock3r** [comment]
https://youtrack.jetbrains.com/issue/IDEA-345096/Add-way-to-obtain-icon-IDs-for-AllIcons-and-similar filed

**Comment by rock3r** [comment]
Done in #430
