### ISSUE TITLE
UI freezes completely when opening a Jewel compose panel in a DialogWrapper on 2024.3.*

### ISSUE THREAD

**Issue by overpas** [JetBrains/jewel#739]
In my [plugin](https://github.com/overpas/svg-to-compose-intellij/tree/update-deps2) there's a problem with running jewel with compose on Intellij 2024.3.+. When a dialog with compose content is shown, no content appears, the whole IDE UI completely freezes and the only option is to kill the process, no crashes in the console as well. The [code](https://github.com/overpas/svg-to-compose-intellij/blob/update-deps2/src/main/kotlin/by/overpass/svgtocomposeintellij/generator/ui/SvgToComposeDialog.kt). I'm using kotlin 2.1.0, compose 1.7.3 and jewel 0.27.0, however this happens on previous versions as well, and only on IJ 2024.3.+ and everything below works fine. Users of the plugin report it as well. What could cause this?

**Comment by rock3r** [comment]
This is a Compose/IJP issue. We've reported it months ago as https://youtrack.jetbrains.com/issue/IJPL-166436/Freeze-in-AWTEventQueue-due-to-MainDispatcherChecker and are waiting for a resolution.

Our current hacky workaround is to invoke this before the window is created, just in case:

```kotlin
 /**
  * Initializes the MainDispatcherChecker in Compose; this must be called from the UI thread in
  * non-modal state. This is a workaround for a freeze in the UI thread that is triggered by using
  * Compose in a dialog before it has been used in a non-modal state.
  *
  * TODO: Delete this when the upstream bug is fixed.
  */
 fun initializeComposeMainDispatcherChecker() {
   object : LifecycleOwner {
     override val lifecycle = LifecycleRegistry(this)
 
     init {
       lifecycle.currentState = Lifecycle.State.STARTED
     }
   }
 }
```
