### ISSUE TITLE
Tab & TabStrip

### ISSUE THREAD

**Issue by rock3r** [JetBrains/jewel#79]
* Tab component
* Basic scrollable TabStrip component

Note: TabStrip doesn't need to handle content changes. It's limited to the tab strip only.

![screenshot of IntUI tab specs](https://github.com/JetBrains/jewel/assets/153802/4afaf3c5-cc7b-4916-9b47-be29f34cf6a5)

**Comment by fscarponi** [comment]
<img width="53" alt="image" src="https://github.com/JetBrains/jewel/assets/36624359/aac4cfbe-9fe8-4750-9587-a5a9ecbf3910">
 it is rounded in the IDE

**Comment by rock3r** [comment]
I swear I had _never_ noticed it is 😱

**Comment by rock3r** [comment]
Moving to m3 since #54 just landed and @fscarponi doesn't have time to do this before the cutoff
