### ISSUE TITLE
Remove usage of data classes

### ISSUE THREAD

**Issue by rock3r** [JetBrains/jewel#83]
They're problematic in terms of binary compat, we should use regular classes with equals and hashcode and toString implemented by hand. See [this article](https://jakewharton.com/public-api-challenges-in-kotlin/) for details.

**Comment by rock3r** [comment]
Work is ongoing, started on 0.5.0, but will continue.

**Comment by rock3r** [comment]
We can use something like https://github.com/drewhamilton/Poko to autogen equals/hashcode/tostring when not using data classes anymore

**Comment by sushkov-pv** [comment]
Lack of the copy function makes overriding theme settings inconvenient. Are there plans to add copy functions for all theme classes?

**Comment by rock3r** [comment]
Not currently, no. You're free to create your own, but we can't because they impact binary compatibility, as the article in the issue explains.
